FROM node:18-alpine

WORKDIR /app

# Install required system dependencies
RUN apk add --no-cache libc6-compat python3 make g++

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

EXPOSE 3111

CMD ["npm", "run", "dev"]
