services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3111:3111"
    environment:
      - NODE_ENV=production # Changed from development to production
      - NEXT_PUBLIC_BACKEND_API_URL=http://backend:5111
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next # Added volume for .next directory
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5111:5111"
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - GITHUB_API_URL=https://api.github.com
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
