FROM node:18-alpine

WORKDIR /app

# Install required system dependencies
RUN apk add --no-cache python3 make g++

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

EXPOSE 5111

CMD ["npm", "run", "start:dev"]
